### ISSUE TITLE
Android does not show shortcuts in RN 0.73.2

### ISSUE THREAD

**Issue by enbochen** [yorickshan/rn-quick-actions#1]
iOS works very well. But for some reasons, Android do not show shortcuts options when long press.
RN version: 0.73.2
Any extra setups are required for the Android?
Thanks!!

**Comment by yorickshan** [comment]
is there kotlinVersion variable in your build.gradle like:

buildscript {
    ext {
        buildToolsVersion = "31.0.0"
        minSdkVersion = 21
        compileSdkVersion = 32
        targetSdkVersion = 26
        kotlinVersion = "1.6.0"
    }
}
